#!/usr/bin/env python3
from rabbit_file_transfer import *
import sys
from progress_meter import  ProgressMeter
def exitUsage():
  print("Usage sending: rftp /local/file rftp://user@host:password/queue_name")
  print("Usage receiving: rftp rftp://user@host:password/ /local/file")
  sys.exit(1)

# parse arguments
if len(sys.argv) < 3:
  exitUsage()
   
source_uri = sys.argv[1]
destination_uri = sys.argv[2]

# setup
rftp = RabbitFileTransfer()
source = rftp.getReader(source_uri)
destination = rftp.getWriter(destination_uri)

if source == None or destination == None:
  exitUsage()

progress = ProgressMeter(source)
progress.start()

# run  
try:
  block = source.getBlock()
  while block != None:
    destination.putBlock(block)
    block = source.getBlock()
except Exception as e:
  print("Transfer error: " + str(e))

progress.stop()
source.close()
destination.close()

print("\nDone!")