#!/usr/bin/env python3
from rabbit_file_transfer import *
import sys
def exitUsage():
  print("Usage receiving: rftp /local/file rftp://user@host:password/queue_name")
  print("Usage sending  : rftp rftp://user@host:password/ /local/file")
  sys.exit(1)

# parse arguments
if len(sys.argv) < 3:
  exitUsage()
   
source_uri = sys.argv[1]
destination_uri = sys.argv[2]

# setup
rftp = RabbitFileTransfer()
source = rftp.getReader(source_uri)
destination = rftp.getWriter(destination_uri)
if source == None or destination == None:
  exitUsage()

# run  
block = source.getBlock()
while block != None:
  destination.putBlock(block)
  block = source.getBlock()
  
print("Done!")